// pipeline {
//     agent any
//     options {
//         skipStagesAfterUnstable()
//     }
//     stages {
//         stage('Build') {
//             steps {
//                 sh 'mvn -B -DskipTests clean package'
//             }
//         }
//         stage('Test') {
//             steps {
//                 sh 'mvn test'
//             }
//             post {
//                 always {
//                     junit 'target/surefire-reports/*.xml'
//                 }
//             }
//         }
//         stage('Deliver') { 
//             steps {
//                 sh './jenkins/scripts/deliver.sh' 
//             }
//         }
//     }
// }


pipeline
{
    agent any

    stages{
        stage('build')
        {
            steps 
            {
                echo "this is build stage"
            }

        }
        stage('test')
        {
            steps 
            {
                echo "this is test stage"
            }
            
        }
        stage('deploy')
        {
            steps 
            {
                echo "this is deploy stage"
            }
            
        }
    }
}